// Haulotte PULSAR DTC - Initial Program Data Repository
// Extracted from PULSAR DTC Presentation and Excel Planning Model

const INITIAL_PROGRAM_DATA = {
  settings: {
    project: "Haulotte PULSAR DTC",
    asOfDate: "2026-09-28", // Local time reference
    workingCalendar: "Mon-Fri",
    baselineTargetMainstream: "2026-12-23",
    baselineTargetSteering: "2027-01-12",
    reviewDurationWd: 1,
    reworkAllowanceWd: 5,
    carryOverLeadTimeWd: 3,
    newCylinderHoseLeadTimeWd: 20,
    mechanicalLeadTimeWd: 30,
    electricalLeadTimeWd: 20
  },
  
  lanes: [
    { id: "routing", name: "Routing", code: "RT", initiative: "INI-110093", owner: "Mechanical Design", annualSavings: 188000 },
    { id: "platform", name: "Platform", code: "PLT", initiative: "INI-108827", owner: "Mechanical Design", annualSavings: 99000 },
    { id: "steering", name: "Steering", code: "ST", initiative: "INI-109505", owner: "Mechanical + Hydraulic", annualSavings: 66500 },
    { id: "inverter", name: "CAN 2 Inverter / P2 XS UCB", code: "SYS", initiative: "INI-109883", owner: "System Design", annualSavings: 254880 },
    { id: "testing", name: "Test & Validation", code: "TST", initiative: "Multiple", owner: "System Test & Validation", annualSavings: 0 },
    { id: "purchasing", name: "TPM / Purchasing", code: "PUR", initiative: "Cross-functional", owner: "TPM / Purchasing", annualSavings: 0 }
  ],

  milestones: [
    {
      id: "MS-M0",
      lane: "purchasing",
      stream: "Project",
      stage: "Stage 1: Design reviews aligned",
      title: "Project inputs available",
      date: "2026-09-28",
      baselineDate: "2026-09-28",
      owner: "TPM",
      achieved: true,
      actualAchievedDate: "2026-09-28",
      predecessors: [],
      notes: "Scope, inputs and pre-studies available."
    },
    {
      id: "RT-M1",
      lane: "routing",
      stream: "Mainstream",
      stage: "Stage 1: Design reviews aligned",
      title: "Routing Design Review OK",
      date: "2026-10-13",
      baselineDate: "2026-10-13",
      owner: "Mechanical Design",
      achieved: false,
      predecessors: ["RT-04"],
      notes: "Routing design accepted."
    },
    {
      id: "PLT-M1",
      lane: "platform",
      stream: "Mainstream",
      stage: "Stage 1: Design reviews aligned",
      title: "Mechanical Design Review OK",
      date: "2026-10-22",
      baselineDate: "2026-10-22",
      owner: "Mechanical Design",
      achieved: false,
      predecessors: ["PLT-06"],
      notes: "Platform / UCB mechanical design accepted."
    },
    {
      id: "SYS-M1",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 1: Design reviews aligned",
      title: "System Design Review OK",
      date: "2026-11-02",
      baselineDate: "2026-10-29",
      owner: "System Design",
      achieved: false,
      predecessors: ["SYS-12"],
      notes: "System definition accepted for prototype."
    },
    {
      id: "ST-OK",
      lane: "steering",
      stream: "Steering",
      stage: "Stage 1: Design reviews aligned",
      title: "Steering Joint Design Review OK",
      date: "2026-10-22",
      baselineDate: "2026-10-22",
      owner: "Mechanical + Hydraulic",
      achieved: false,
      predecessors: ["ST-DR"],
      notes: "Joint Mechanical + Hydraulic design accepted for Narrow and Wide."
    },
    {
      id: "PLT-M2",
      lane: "platform",
      stream: "Mainstream",
      stage: "Stage 2: Prototype ready to order",
      title: "Platform Prototype Ready to Order",
      date: "2026-10-27",
      baselineDate: "2026-10-27",
      owner: "TPM / Purchasing",
      achieved: false,
      predecessors: ["PLT-08"],
      notes: "Platform prototype definition released."
    },
    {
      id: "SYS-M2",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 2: Prototype ready to order",
      title: "General Harness Ready to Order",
      date: "2026-11-04",
      baselineDate: "2026-11-02",
      owner: "TPM / Purchasing",
      achieved: false,
      predecessors: ["SYS-14"],
      notes: "General harness can be ordered."
    },
    {
      id: "SYS-M4",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 2: Prototype ready to order",
      title: "UP/DOWN Cable Ready to Order",
      date: "2026-11-04",
      baselineDate: "2026-11-02",
      owner: "TPM / Purchasing",
      achieved: false,
      predecessors: ["SYS-17"],
      notes: "UP/DOWN cable can be ordered."
    },
    {
      id: "ST-BUNDLE-RD",
      lane: "steering",
      stream: "Steering",
      stage: "Stage 2: Prototype ready to order",
      title: "Steering Bundle Ready to Order",
      date: "2026-10-27",
      baselineDate: "2026-10-27",
      owner: "TPM / Purchasing",
      achieved: false,
      predecessors: ["ST-CH-DEF", "ST-PV-DEF", "ST-SM-DEF", "ST-CY-DEF", "ST-HO-DEF"],
      notes: "All steering bundle prototype definitions released."
    },
    {
      id: "INV-M1",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "Inverter Prototype Available",
      date: "2026-10-27",
      baselineDate: "2026-10-27",
      owner: "TPM / Purchasing",
      achieved: false,
      prototypeId: "PUR-01",
      predecessors: ["INV-02"],
      notes: "Inverter physically available."
    },
    {
      id: "UCB-M1",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "UCB XS Prototype Available",
      date: "2026-10-27",
      baselineDate: "2026-10-27",
      owner: "TPM / Purchasing",
      achieved: false,
      prototypeId: "PUR-02",
      predecessors: ["UCB-02"],
      notes: "UCB XS physically available."
    },
    {
      id: "PLT-M3",
      lane: "platform",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "Platform Prototype Available",
      date: "2026-12-09",
      baselineDate: "2026-12-09",
      owner: "TPM / Purchasing",
      achieved: false,
      prototypeId: "PUR-03",
      predecessors: ["PLT-10"],
      notes: "Platform prototype physically available."
    },
    {
      id: "SYS-M3",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "General Harness Available",
      date: "2026-12-03",
      baselineDate: "2026-12-01",
      owner: "TPM / Purchasing",
      achieved: false,
      prototypeId: "PUR-04",
      predecessors: ["SYS-16"],
      notes: "General harness physically available."
    },
    {
      id: "SYS-M5",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "UP/DOWN Cable Available",
      date: "2026-12-03",
      baselineDate: "2026-12-01",
      owner: "TPM / Purchasing",
      achieved: false,
      prototypeId: "PUR-05",
      predecessors: ["SYS-19"],
      notes: "UP/DOWN cable physically available."
    },
    {
      id: "SP-M1",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "Spiral Cable Available",
      date: "2026-12-02",
      baselineDate: "2026-12-02",
      owner: "TPM / Purchasing",
      achieved: false,
      prototypeId: "PUR-06",
      predecessors: ["SP-02"],
      notes: "Spiral cable physically available."
    },
    {
      id: "SW-M1",
      lane: "inverter",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "Prototype Software Ready",
      date: "2026-11-09",
      baselineDate: "2026-11-09",
      owner: "Software Design",
      achieved: false,
      predecessors: ["SW-05"],
      notes: "Prototype software build ready for integrated test."
    },
    {
      id: "TST-M1",
      lane: "testing",
      stream: "Mainstream",
      stage: "Stage 3: Prototype available",
      title: "Complete Electrical Prototype Set Available",
      date: "2026-12-03",
      baselineDate: "2026-12-01",
      owner: "System Test & Validation",
      achieved: false,
      predecessors: ["INV-M1", "UCB-M1", "SYS-M3", "SYS-M5", "SP-M1", "SW-M1"],
      notes: "All electrical components + software ready. Test entry gate."
    },
    {
      id: "ST-BUNDLE",
      lane: "steering",
      stream: "Steering",
      stage: "Stage 3: Prototype available",
      title: "Complete Steering Bundle Available",
      date: "2026-12-09",
      baselineDate: "2026-12-09",
      owner: "Mechanical + Hydraulic",
      achieved: false,
      predecessors: ["ST-CH-AV", "ST-PV-AV", "ST-SM-AV", "ST-CY-AV", "ST-HO-AV"],
      notes: "Narrow & Wide chassis, pivots, mechanism, cylinder and hoses physically available."
    },
    {
      id: "PLT-M4",
      lane: "platform",
      stream: "Mainstream",
      stage: "Stage 4: Validation complete",
      title: "Platform Validation Complete",
      date: "2026-12-16",
      baselineDate: "2026-12-16",
      owner: "Mechanical Test & Validation",
      achieved: false,
      predecessors: ["PLT-11"],
      notes: "Platform mechanically validated."
    },
    {
      id: "TST-M2",
      lane: "testing",
      stream: "Mainstream",
      stage: "Stage 4: Validation complete",
      title: "System Validation Complete",
      date: "2026-12-15",
      baselineDate: "2026-12-11",
      owner: "System Test & Validation",
      achieved: false,
      predecessors: ["TST-02"],
      notes: "Integrated system validated."
    },
    {
      id: "ST-VALID",
      lane: "steering",
      stream: "Steering",
      stage: "Stage 4: Validation complete",
      title: "Steering Validation Complete",
      date: "2027-01-08",
      baselineDate: "2027-01-08",
      owner: "Mechanical Test & Validation",
      achieved: false,
      predecessors: ["ST-T5"],
      notes: "Narrow and Wide endurance & functional testing complete."
    },
    {
      id: "RT-M2",
      lane: "routing",
      stream: "Mainstream",
      stage: "Stage 5: Serial TR delivered",
      title: "Routing Serial TR delivered",
      date: "2026-10-15",
      baselineDate: "2026-10-15",
      owner: "TPM / Mechanical",
      achieved: false,
      predecessors: ["RT-06"],
      notes: "Routing technical release package delivered."
    },
    {
      id: "PLT-M5",
      lane: "platform",
      stream: "Mainstream",
      stage: "Stage 5: Serial TR delivered",
      title: "Platform Serial TR delivered",
      date: "2026-12-18",
      baselineDate: "2026-12-18",
      owner: "TPM / Mechanical",
      achieved: false,
      predecessors: ["PLT-13"],
      notes: "Platform technical release delivered."
    },
    {
      id: "MS-END",
      lane: "testing",
      stream: "Mainstream",
      stage: "Stage 5: Serial TR delivered",
      title: "Mainstream Serial TR delivered",
      date: "2026-12-23",
      baselineDate: "2026-12-23",
      owner: "TPM / Engineering",
      achieved: false,
      isEndpoint: true,
      predecessors: ["MS-TR"],
      notes: "Mainstream Serial Technical Release delivered independently of Steering."
    },
    {
      id: "ST-END",
      lane: "steering",
      stream: "Steering",
      stage: "Stage 5: Serial TR delivered",
      title: "Steering Serial TR delivered",
      date: "2027-01-12",
      baselineDate: "2027-01-12",
      owner: "TPM / Engineering",
      achieved: false,
      isEndpoint: true,
      predecessors: ["ST-TR"],
      notes: "Steering Serial Technical Release delivered independently of Mainstream."
    }
  ],

  activities: [
    // ----------------- ROUTING LANE (INI-110093) -----------------
    {
      id: "RT-01",
      lane: "routing",
      stream: "Mainstream",
      initiative: "INI-110093",
      title: "Quick routing analysis",
      owner: "Mechanical Design",
      startDate: "2026-09-28",
      expectedFinishDate: "2026-10-02",
      durationWd: 5,
      remainingWd: 5,
      progress: 0,
      blocked: false,
      nextAction: "Analyze arms routing impact from new UP/DOWN cable specifications.",
      predecessors: ["MS-M0"],
      checklist: [
        { text: "Assess UP/DOWN routing envelope in scissor arms", done: false },
        { text: "Check bend radius and clamp positions", done: false }
      ]
    },
    {
      id: "RT-02",
      lane: "routing",
      stream: "Mainstream",
      initiative: "INI-110093",
      title: "Integrate System Design feedback on UP/DOWN cable",
      owner: "Mechanical Design",
      startDate: "2026-10-06",
      expectedFinishDate: "2026-10-07",
      durationWd: 2,
      remainingWd: 2,
      progress: null, // Unknown progress remains blank
      blocked: false,
      nextAction: "Wait for SYS-02 fast-track cable size & routing definition.",
      predecessors: ["RT-01", "SYS-02"],
      checklist: [
        { text: "Confirm connector clearance through scissor channels", done: false }
      ]
    },
    {
      id: "RT-03",
      lane: "routing",
      stream: "Mainstream",
      initiative: "INI-110093",
      title: "Detailed routing update",
      owner: "Mechanical Design",
      startDate: "2026-10-08",
      expectedFinishDate: "2026-10-12",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Finalize routing 3D models and clamp drawings.",
      predecessors: ["RT-02"],
      checklist: []
    },
    {
      id: "RT-04",
      lane: "routing",
      stream: "Mainstream",
      initiative: "INI-110093",
      title: "Routing Design Review",
      owner: "Mechanical Design",
      startDate: "2026-10-13",
      expectedFinishDate: "2026-10-13",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Conduct formal cross-functional routing review for GO decision.",
      predecessors: ["RT-03"],
      checklist: []
    },
    {
      id: "RT-06",
      lane: "routing",
      stream: "Mainstream",
      initiative: "INI-110093",
      title: "Prepare Routing Serial TR",
      owner: "Mechanical Design",
      startDate: "2026-10-14",
      expectedFinishDate: "2026-10-15",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Assemble drawings, BOM changes and technical release documentation.",
      predecessors: ["RT-M1"],
      checklist: []
    },

    // ----------------- PLATFORM LANE (INI-108827) -----------------
    {
      id: "PLT-01",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Platform design study (options & labels review)",
      owner: "Mechanical Design",
      startDate: "2026-09-28",
      expectedFinishDate: "2026-10-02",
      durationWd: 5,
      remainingWd: 5,
      progress: 0,
      blocked: false,
      nextAction: "Evaluate COMPACT options, labels and implantation constraints.",
      predecessors: ["MS-M0"],
      checklist: [
        { text: "Review COMPACT platform options compatibility", done: false },
        { text: "Inspect regulatory and control label space", done: false }
      ]
    },
    {
      id: "PLT-02",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Detailed platform mechanical design",
      owner: "Mechanical Design",
      startDate: "2026-10-05",
      expectedFinishDate: "2026-10-16",
      durationWd: 10,
      remainingWd: 10,
      progress: null,
      blocked: false,
      nextAction: "Complete platform structure CAD and mounting interfaces.",
      predecessors: ["PLT-01"],
      checklist: []
    },
    {
      id: "PLT-03",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "COMPACT options / labels / implantation checks",
      owner: "Mechanical Design",
      startDate: "2026-09-30",
      expectedFinishDate: "2026-10-06",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Confirm no clash with auxiliary options.",
      predecessors: ["PLT-01"],
      checklist: []
    },
    {
      id: "PLT-04",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "UCB XS mechanical integration & mounting",
      owner: "Mechanical Design",
      startDate: "2026-10-05",
      expectedFinishDate: "2026-10-09",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Design UCB XS bracket and cable entrance protection.",
      predecessors: ["PLT-01"],
      checklist: []
    },
    {
      id: "PLT-05",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Mechanical Design consolidation",
      owner: "Mechanical Design",
      startDate: "2026-10-19",
      expectedFinishDate: "2026-10-21",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Consolidate 3D models and review tolerance stack-up.",
      predecessors: ["PLT-02", "PLT-03", "PLT-04"],
      checklist: []
    },
    {
      id: "PLT-06",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Platform Mechanical Design Review",
      owner: "Mechanical Design",
      startDate: "2026-10-22",
      expectedFinishDate: "2026-10-22",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Conduct design freeze review for platform prototype.",
      predecessors: ["PLT-05"],
      checklist: []
    },
    {
      id: "PLT-08",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Platform prototype definition & release package",
      owner: "Mechanical Design",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-27",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Release 2D fabrication drawings and PO specifications.",
      predecessors: ["PLT-M1"],
      checklist: []
    },
    {
      id: "PLT-09",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Procurement Launch – platform prototype",
      owner: "TPM / Purchasing",
      startDate: "2026-10-28",
      expectedFinishDate: "2026-10-28",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Issue Purchase Order to supplier.",
      predecessors: ["PLT-M2"],
      checklist: []
    },
    {
      id: "PLT-10",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Procurement Lead Time – platform prototype",
      owner: "Purchasing / Supplier",
      startDate: "2026-10-29",
      expectedFinishDate: "2026-12-09",
      durationWd: 30,
      remainingWd: 30,
      progress: null,
      blocked: false,
      nextAction: "Track fabrication and shipping.",
      prototypeId: "PUR-03",
      predecessors: ["PLT-09"],
      checklist: []
    },
    {
      id: "PLT-11",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Platform assembly / fit / functional checks",
      owner: "Mechanical Test & Validation",
      startDate: "2026-12-10",
      expectedFinishDate: "2026-12-16",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Assemble platform prototype and test UCB XS fitment.",
      predecessors: ["PLT-M3", "UCB-M1"],
      checklist: [
        { text: "Mount platform onto scissor structure", done: false },
        { text: "Fit UCB XS control box & check clearance", done: false },
        { text: "Verify label readability and guard rails", done: false }
      ]
    },
    {
      id: "PLT-13",
      lane: "platform",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Prepare Platform Serial TR",
      owner: "Mechanical Design",
      startDate: "2026-12-17",
      expectedFinishDate: "2026-12-18",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Finalize serial documentation for Platform release.",
      predecessors: ["PLT-M4"],
      checklist: []
    },

    // ----------------- CAN 2 INVERTER / P2 XS UCB (INI-109883) -----------------
    {
      id: "INV-01",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Launch – inverter prototype",
      owner: "TPM / Purchasing",
      startDate: "2026-09-29",
      expectedFinishDate: "2026-09-29",
      durationWd: 1,
      remainingWd: 1,
      progress: 0,
      blocked: false,
      nextAction: "Send PO to inverter supplier based on ready spec.",
      predecessors: ["MS-M0"],
      checklist: []
    },
    {
      id: "INV-02",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Lead Time – inverter prototype",
      owner: "Purchasing / Supplier",
      startDate: "2026-09-30",
      expectedFinishDate: "2026-10-27",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Follow up supplier production and firmware pre-flash.",
      prototypeId: "PUR-01",
      predecessors: ["INV-01"],
      checklist: []
    },
    {
      id: "UCB-01",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Procurement Launch – UCB XS prototype",
      owner: "TPM / Purchasing",
      startDate: "2026-09-29",
      expectedFinishDate: "2026-09-29",
      durationWd: 1,
      remainingWd: 1,
      progress: 0,
      blocked: false,
      nextAction: "Issue prototype PO for UCB XS hardware.",
      predecessors: ["MS-M0"],
      checklist: []
    },
    {
      id: "UCB-02",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-108827",
      title: "Procurement Lead Time – UCB XS prototype",
      owner: "Purchasing / Supplier",
      startDate: "2026-09-30",
      expectedFinishDate: "2026-10-27",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Expedite prototype fabrication.",
      prototypeId: "PUR-02",
      predecessors: ["UCB-01"],
      checklist: []
    },
    {
      id: "SYS-01",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "System impact analysis",
      owner: "System Design",
      startDate: "2026-09-28",
      expectedFinishDate: "2026-09-30",
      durationWd: 3,
      remainingWd: 3,
      progress: 0,
      blocked: false,
      nextAction: "Map CAN 2 bus topography, power distribution and signal routing.",
      predecessors: ["MS-M0"],
      checklist: []
    },
    {
      id: "SYS-02",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Preliminary UP/DOWN cable size & routing definition (fast-track)",
      owner: "System Design",
      startDate: "2026-10-01",
      expectedFinishDate: "2026-10-05",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Fast-track cable cross-section & connector details to Mechanical team.",
      predecessors: ["SYS-01"],
      checklist: []
    },
    {
      id: "SYS-03",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "System architecture definition",
      owner: "System Design",
      startDate: "2026-10-01",
      expectedFinishDate: "2026-10-09",
      durationWd: 7,
      remainingWd: 7,
      progress: null,
      blocked: false,
      nextAction: "Define complete machine electrical network architecture.",
      predecessors: ["SYS-01"],
      checklist: []
    },
    {
      id: "SYS-04",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Inverter + general harness integration definition",
      owner: "System Design",
      startDate: "2026-10-12",
      expectedFinishDate: "2026-10-16",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Define pinouts and interconnections between inverter and harness.",
      predecessors: ["SYS-03"],
      checklist: []
    },
    {
      id: "SYS-05",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Detailed general harness definition",
      owner: "System Design",
      startDate: "2026-10-19",
      expectedFinishDate: "2026-10-27",
      durationWd: 7,
      remainingWd: 7,
      progress: null,
      blocked: false,
      nextAction: "Complete 2D harness manufacturing drawings.",
      predecessors: ["SYS-04"],
      checklist: []
    },
    {
      id: "SYS-06",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Detailed UP/DOWN cable definition",
      owner: "System Design",
      startDate: "2026-10-12",
      expectedFinishDate: "2026-10-16",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Finalize cable shielding, jacket durability and connectors.",
      predecessors: ["SYS-02", "SYS-03"],
      checklist: []
    },
    {
      id: "SYS-07",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Spiral cable interface assessment",
      owner: "System Design",
      startDate: "2026-10-12",
      expectedFinishDate: "2026-10-14",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Assess compatibility of existing spiral cable with CAN 2 baud rate.",
      predecessors: ["SYS-03"],
      checklist: []
    },
    {
      id: "SYS-08",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "UCB XS electrical / system interface definition",
      owner: "System Design",
      startDate: "2026-10-12",
      expectedFinishDate: "2026-10-16",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Define electrical connector, power supply and CAN bus termination.",
      predecessors: ["SYS-03"],
      checklist: []
    },
    {
      id: "SYS-09",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Electrical schematics / architecture update",
      owner: "System Design",
      startDate: "2026-10-19",
      expectedFinishDate: "2026-10-23",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Update master electrical CAD schematics.",
      predecessors: ["SYS-04", "SYS-06", "SYS-07", "SYS-08"],
      checklist: []
    },
    {
      id: "SYS-10",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Backward compatibility scenarios + configuration safeguards",
      owner: "System Design",
      startDate: "2026-10-19",
      expectedFinishDate: "2026-10-23",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Verify poka-yoke detection for mixed old/new UCB setups (Risk R6).",
      predecessors: ["SYS-06", "SYS-08"],
      checklist: []
    },
    {
      id: "SYS-11",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "System Design consolidation",
      owner: "System Design",
      startDate: "2026-10-28",
      expectedFinishDate: "2026-10-30",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Consolidate electrical schematics, harness prints and safeguards.",
      predecessors: ["SYS-09", "SYS-10", "SYS-05"],
      checklist: []
    },
    {
      id: "SYS-12",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "System Design Review",
      owner: "System Design",
      startDate: "2026-11-02",
      expectedFinishDate: "2026-11-02",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Cross-team GO / NOK review for prototype harness manufacturing.",
      predecessors: ["SYS-11"],
      checklist: []
    },
    {
      id: "SYS-14",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "General harness prototype definition",
      owner: "System Design",
      startDate: "2026-11-03",
      expectedFinishDate: "2026-11-04",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Release build package to harness manufacturer.",
      predecessors: ["SYS-M1"],
      checklist: []
    },
    {
      id: "SYS-15",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Launch – general harness",
      owner: "TPM / Purchasing",
      startDate: "2026-11-05",
      expectedFinishDate: "2026-11-05",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Place prototype order.",
      predecessors: ["SYS-M2"],
      checklist: []
    },
    {
      id: "SYS-16",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Lead Time – general harness",
      owner: "Purchasing / Supplier",
      startDate: "2026-11-06",
      expectedFinishDate: "2026-12-03",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Follow up delivery.",
      prototypeId: "PUR-04",
      predecessors: ["SYS-15"],
      checklist: []
    },
    {
      id: "SYS-17",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "UP/DOWN cable prototype definition",
      owner: "System Design",
      startDate: "2026-11-03",
      expectedFinishDate: "2026-11-04",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Release cable build specs.",
      predecessors: ["SYS-M1"],
      checklist: []
    },
    {
      id: "SYS-18",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Launch – UP/DOWN cable",
      owner: "TPM / Purchasing",
      startDate: "2026-11-05",
      expectedFinishDate: "2026-11-05",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Issue PO for UP/DOWN cable prototype.",
      predecessors: ["SYS-M4"],
      checklist: []
    },
    {
      id: "SYS-19",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Lead Time – UP/DOWN cable",
      owner: "Purchasing / Supplier",
      startDate: "2026-11-06",
      expectedFinishDate: "2026-12-03",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Expedite delivery for integrated test.",
      prototypeId: "PUR-05",
      predecessors: ["SYS-18"],
      checklist: []
    },
    {
      id: "SP-01",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Spiral cable sourcing / stock confirmation",
      owner: "System Design",
      startDate: "2026-11-03",
      expectedFinishDate: "2026-11-04",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Verify warehouse inventory or order prototype.",
      predecessors: ["SYS-M6"],
      checklist: []
    },
    {
      id: "SP-02",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Procurement Lead Time — spiral cable",
      owner: "System Design",
      startDate: "2026-11-05",
      expectedFinishDate: "2026-12-02",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Retrieve from stock or track delivery.",
      prototypeId: "PUR-06",
      predecessors: ["SP-01"],
      checklist: []
    },
    {
      id: "SW-01",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Software impact analysis",
      owner: "Software Design",
      startDate: "2026-10-01",
      expectedFinishDate: "2026-10-05",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Identify required software modules for new inverter and CAN 2 stack.",
      predecessors: ["SYS-03"],
      checklist: []
    },
    {
      id: "SW-02",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Architecture / CAN protocol adaptation",
      owner: "Software Design",
      startDate: "2026-10-12",
      expectedFinishDate: "2026-10-23",
      durationWd: 10,
      remainingWd: 10,
      progress: null,
      blocked: false,
      nextAction: "Implement new inverter communication and diagnostic messages.",
      predecessors: ["SYS-03", "SW-01"],
      checklist: []
    },
    {
      id: "SW-03",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "UCB selection / detection + poka-yoke safeguards",
      owner: "Software Design",
      startDate: "2026-10-26",
      expectedFinishDate: "2026-10-30",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Code auto-detection of UCB type and safety lockout if mismatch.",
      predecessors: ["SYS-10"],
      checklist: []
    },
    {
      id: "SW-04",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Prototype software build",
      owner: "Software Design",
      startDate: "2026-11-02",
      expectedFinishDate: "2026-11-06",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Compile and bench-test release candidate build.",
      predecessors: ["SW-02", "SW-03"],
      checklist: []
    },
    {
      id: "SW-05",
      lane: "inverter",
      stream: "Mainstream",
      initiative: "INI-109883",
      title: "Software Review",
      owner: "Software Design",
      startDate: "2026-11-09",
      expectedFinishDate: "2026-11-09",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Review software test results for test entry.",
      predecessors: ["SW-04"],
      checklist: []
    },

    // ----------------- TEST & VALIDATION LANE -----------------
    {
      id: "TST-01",
      lane: "testing",
      stream: "Mainstream",
      initiative: "Multiple",
      title: "Prototype machine assembly / system integration",
      owner: "System Test & Validation",
      startDate: "2026-12-04",
      expectedFinishDate: "2026-12-08",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Install electrical prototype set (inverter, harnesses, UCB XS) into test bench machine.",
      predecessors: ["TST-M1"],
      checklist: [
        { text: "Mount inverter and connect primary power harnesses", done: false },
        { text: "Route UP/DOWN cable through scissor arm", done: false },
        { text: "Install UCB XS and flash prototype software", done: false }
      ]
    },
    {
      id: "TST-02",
      lane: "testing",
      stream: "Mainstream",
      initiative: "Multiple",
      title: "Integrated system functionality test",
      owner: "System Test & Validation",
      startDate: "2026-12-09",
      expectedFinishDate: "2026-12-15",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Run functional qualification: drive, lift, CAN communication, diagnostics.",
      predecessors: ["TST-01"],
      checklist: [
        { text: "Validate drive controller response and ramps", done: false },
        { text: "Validate lift/lower controls and safeguards", done: false },
        { text: "Verify CAN bus load and fault injection behavior", done: false }
      ]
    },
    {
      id: "TST-05",
      lane: "testing",
      stream: "Mainstream",
      initiative: "Multiple",
      title: "Prepare Mainstream Serial TR package",
      owner: "TPM + Technical Teams",
      startDate: "2026-12-17",
      expectedFinishDate: "2026-12-21",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Compile validation reports and draft technical release documentation.",
      predecessors: ["TST-M2", "PLT-M4", "RT-M1"],
      checklist: []
    },
    {
      id: "MS-TR",
      lane: "testing",
      stream: "Mainstream",
      initiative: "Multiple",
      title: "Mainstream Serial TR issuance / approval",
      owner: "TPM / Engineering",
      startDate: "2026-12-22",
      expectedFinishDate: "2026-12-23",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Formal Engineering Director sign-off and serial ERP release.",
      predecessors: ["TST-M3", "RT-M2", "PLT-M5"],
      checklist: []
    },

    // ----------------- STEERING LANE (INI-109505) -----------------
    // Shared scope for Narrow & Wide. Preserves physical assembly sequence: Chassis -> Pivots -> Cylinder & Steering Mechanism -> Hoses
    {
      id: "ST-D1",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Steering concept study (Narrow & Wide)",
      owner: "Mechanical Design",
      startDate: "2026-09-28",
      expectedFinishDate: "2026-10-02",
      durationWd: 5,
      remainingWd: 5,
      progress: 0,
      blocked: false,
      nextAction: "Harmonize single-cylinder steering kinematics across Narrow and Wide models.",
      predecessors: ["MS-M0"],
      checklist: [
        { text: "Narrow chassis steering geometry evaluation", done: false },
        { text: "Wide chassis steering geometry evaluation", done: false }
      ]
    },
    {
      id: "ST-H1",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hydraulic architecture study",
      owner: "Hydraulic System Design",
      startDate: "2026-09-28",
      expectedFinishDate: "2026-10-02",
      durationWd: 5,
      remainingWd: 5,
      progress: 0,
      blocked: false,
      nextAction: "Analyze steering pressure, flow requirements and valve block ports.",
      predecessors: ["MS-M0"],
      checklist: []
    },
    {
      id: "ST-D2",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Detailed steering mechanism design",
      owner: "Mechanical Design",
      startDate: "2026-10-05",
      expectedFinishDate: "2026-10-16",
      durationWd: 10,
      remainingWd: 10,
      progress: null,
      blocked: false,
      nextAction: "Design tie rods, central link and knuckle brackets.",
      predecessors: ["ST-D1"],
      checklist: [
        { text: "Narrow mechanism detail design", done: false },
        { text: "Wide mechanism detail design", done: false }
      ]
    },
    {
      id: "ST-D3",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Chassis detailed design (Narrow & Wide)",
      owner: "Mechanical Design",
      startDate: "2026-10-07",
      expectedFinishDate: "2026-10-16",
      durationWd: 8,
      remainingWd: 8,
      progress: null,
      blocked: false,
      nextAction: "Adapt chassis front structure with minimal modifications (Decision D3).",
      predecessors: ["ST-D2"],
      checklist: [
        { text: "Narrow chassis modifications minimized", done: false },
        { text: "Wide chassis modifications minimized", done: false }
      ]
    },
    {
      id: "ST-D4",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Pivot set / mounting interfaces design",
      owner: "Mechanical Design",
      startDate: "2026-10-08",
      expectedFinishDate: "2026-10-14",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Design kingpin pivots, bushings and kingpin inclination.",
      predecessors: ["ST-D2"],
      checklist: [
        { text: "Narrow pivot set interface", done: false },
        { text: "Wide pivot set interface", done: false }
      ]
    },
    {
      id: "ST-H2",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Cylinder definition & carry-over assessment",
      owner: "Hydraulic System Design",
      startDate: "2026-10-05",
      expectedFinishDate: "2026-10-09",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Assess carry-over of existing cylinder vs new part (Decisions D1-N, D1-W).",
      predecessors: ["ST-H1"],
      checklist: [
        { text: "Narrow cylinder carry-over technical suitability", done: false },
        { text: "Wide cylinder carry-over technical suitability", done: false }
      ]
    },
    {
      id: "ST-CDEC",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Cylinder sourcing decision accepted",
      owner: "Hydraulic System Design",
      startDate: "2026-10-09",
      expectedFinishDate: "2026-10-09",
      durationWd: 0,
      remainingWd: 0,
      progress: null,
      blocked: false,
      nextAction: "Confirm Carry-over vs New part decision for Narrow and Wide.",
      predecessors: ["ST-H2"],
      checklist: []
    },
    {
      id: "ST-H3",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hoses / fittings definition & carry-over assessment",
      owner: "Hydraulic System Design",
      startDate: "2026-10-05",
      expectedFinishDate: "2026-10-09",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Check hose length and standard fittings reuse (Decisions D2-N, D2-W).",
      predecessors: ["ST-H2"],
      checklist: []
    },
    {
      id: "ST-HDEC",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hoses sourcing decision accepted",
      owner: "Hydraulic System Design",
      startDate: "2026-10-09",
      expectedFinishDate: "2026-10-09",
      durationWd: 0,
      remainingWd: 0,
      progress: null,
      blocked: false,
      nextAction: "Confirm hose carry-over.",
      predecessors: ["ST-H3"],
      checklist: []
    },
    {
      id: "ST-H4",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hydraulic hose routing definition",
      owner: "Hydraulic System Design",
      startDate: "2026-10-12",
      expectedFinishDate: "2026-10-16",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Check dynamic steering hose bend angles to avoid chafing.",
      predecessors: ["ST-H3", "ST-D3"],
      checklist: []
    },
    {
      id: "ST-D5",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Packaging / clearances / interface consolidation",
      owner: "Mechanical Design",
      startDate: "2026-10-19",
      expectedFinishDate: "2026-10-21",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Consolidate chassis, pivots, cylinder and hose routing in 3D assembly.",
      predecessors: ["ST-D2", "ST-D3", "ST-D4", "ST-H4", "ST-CDEC", "ST-HDEC"],
      checklist: []
    },
    {
      id: "ST-DR",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Joint Mechanical + Hydraulic Design Review",
      owner: "Mechanical + Hydraulic",
      startDate: "2026-10-22",
      expectedFinishDate: "2026-10-22",
      durationWd: 1,
      remainingWd: 1,
      progress: null,
      blocked: false,
      nextAction: "Joint engineering sign-off for prototype bundle build.",
      predecessors: ["ST-D5"],
      checklist: []
    },
    {
      id: "ST-RFQ",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Supplier RFQ / adaptation pricing preparation",
      owner: "TPM / Purchasing",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-26",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Send technical specs to chassis and cylinder suppliers for pricing.",
      predecessors: ["ST-OK"],
      checklist: []
    },
    {
      id: "ST-QUOTE",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Supplier quotation / pricing discussion",
      owner: "TPM / Purchasing",
      startDate: "2026-10-27",
      expectedFinishDate: "2026-11-02",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Negotiate adaptation tooling and piece costs.",
      predecessors: ["ST-RFQ"],
      checklist: []
    },
    {
      id: "ST-COST",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Adaptation cost impact confirmed",
      owner: "TPM / Purchasing",
      startDate: "2026-11-02",
      expectedFinishDate: "2026-11-02",
      durationWd: 0,
      remainingWd: 0,
      progress: null,
      blocked: false,
      nextAction: "Update business case with confirmed supplier quotes.",
      predecessors: ["ST-QUOTE"],
      checklist: []
    },

    // Steering Prototype Bundle Procurement Definitions
    {
      id: "ST-CH-DEF",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Chassis prototype definition (Narrow & Wide)",
      owner: "Mechanical Design",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-27",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Release chassis prototype welding drawings.",
      predecessors: ["ST-OK"],
      checklist: [
        { text: "Narrow chassis prototype drawings released", done: false },
        { text: "Wide chassis prototype drawings released", done: false }
      ]
    },
    {
      id: "ST-PV-DEF",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Pivot set prototype definition (Narrow & Wide)",
      owner: "Mechanical Design",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-27",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Release pivot set machining drawings.",
      predecessors: ["ST-OK"],
      checklist: []
    },
    {
      id: "ST-SM-DEF",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Steering mechanism prototype definition (Narrow & Wide)",
      owner: "Mechanical Design",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-27",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Release steering linkage drawings.",
      predecessors: ["ST-OK"],
      checklist: []
    },
    {
      id: "ST-CY-DEF",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hydraulic cylinder prototype definition (Narrow & Wide)",
      owner: "Hydraulic System Design",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-27",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Release cylinder specifications / confirm stock retrieval.",
      predecessors: ["ST-OK"],
      checklist: []
    },
    {
      id: "ST-HO-DEF",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hoses / fittings / routing parts prototype definition",
      owner: "Hydraulic System Design",
      startDate: "2026-10-23",
      expectedFinishDate: "2026-10-27",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Release hose cut sheets and fitting BOM.",
      predecessors: ["ST-OK"],
      checklist: []
    },

    // Steering Procurement Lead Time items (feeding into milestones)
    {
      id: "ST-CH-LT",
      lane: "purchasing",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Procurement Lead Time — Chassis (Narrow & Wide)",
      owner: "Purchasing / Supplier",
      startDate: "2026-10-29",
      expectedFinishDate: "2026-12-09",
      durationWd: 30,
      remainingWd: 30,
      progress: null,
      blocked: false,
      nextAction: "Track prototype frame manufacturing.",
      prototypeId: "PUR-07",
      predecessors: ["ST-CH-DEF"],
      checklist: [
        { text: "Narrow chassis fabricated and delivered", done: false },
        { text: "Wide chassis fabricated and delivered", done: false }
      ]
    },
    {
      id: "ST-PV-LT",
      lane: "purchasing",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Procurement Lead Time — Pivot Sets (Narrow & Wide)",
      owner: "Purchasing / Supplier",
      startDate: "2026-10-29",
      expectedFinishDate: "2026-12-09",
      durationWd: 30,
      remainingWd: 30,
      progress: null,
      blocked: false,
      nextAction: "Track pivot machining.",
      prototypeId: "PUR-08",
      predecessors: ["ST-PV-DEF"],
      checklist: []
    },
    {
      id: "ST-SM-LT",
      lane: "purchasing",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Procurement Lead Time — Steering Mechanism (Narrow & Wide)",
      owner: "Purchasing / Supplier",
      startDate: "2026-10-29",
      expectedFinishDate: "2026-12-09",
      durationWd: 30,
      remainingWd: 30,
      progress: null,
      blocked: false,
      nextAction: "Track linkage fabrication.",
      prototypeId: "PUR-09",
      predecessors: ["ST-SM-DEF"],
      checklist: []
    },
    {
      id: "ST-CY-LT",
      lane: "purchasing",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Procurement Lead Time — Hydraulic Cylinders (Narrow & Wide)",
      owner: "Purchasing / Supplier",
      startDate: "2026-10-29",
      expectedFinishDate: "2026-11-25",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Receive test cylinder units.",
      prototypeId: "PUR-10",
      predecessors: ["ST-CY-DEF"],
      checklist: []
    },
    {
      id: "ST-HO-LT",
      lane: "purchasing",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Procurement Lead Time — Hoses & Fittings (Narrow & Wide)",
      owner: "Purchasing / Supplier",
      startDate: "2026-10-29",
      expectedFinishDate: "2026-11-25",
      durationWd: 20,
      remainingWd: 20,
      progress: null,
      blocked: false,
      nextAction: "Crimp hoses and package fittings kit.",
      prototypeId: "PUR-11",
      predecessors: ["ST-HO-DEF"],
      checklist: []
    },

    // Physical Steering Assembly & Validation Sequence (Strict sequence: Chassis -> Pivots -> Cylinder & Steering Mechanism -> Hoses)
    {
      id: "ST-T1",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Pivot assembly on chassis (Narrow & Wide)",
      owner: "Mechanical Test & Validation",
      startDate: "2026-12-10",
      expectedFinishDate: "2026-12-11",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Mount pivot sets onto variant chassis structures.",
      predecessors: ["ST-CH-LT", "ST-PV-LT"],
      checklist: [
        { text: "Narrow chassis pivot assembly & alignment check", done: false },
        { text: "Wide chassis pivot assembly & alignment check", done: false }
      ]
    },
    {
      id: "ST-T2",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Cylinder and steering mechanism assembly (Narrow & Wide)",
      owner: "Mechanical Test & Validation",
      startDate: "2026-12-14",
      expectedFinishDate: "2026-12-15",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Assemble cylinder and linkage into pivoted chassis.",
      predecessors: ["ST-T1", "ST-CY-LT", "ST-SM-LT"],
      checklist: [
        { text: "Narrow cylinder and steering mechanism installation", done: false },
        { text: "Wide cylinder and steering mechanism installation", done: false }
      ]
    },
    {
      id: "ST-T3",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Hose installation / routing and fit checks (Narrow & Wide)",
      owner: "Mechanical Test & Validation",
      startDate: "2026-12-16",
      expectedFinishDate: "2026-12-18",
      durationWd: 3,
      remainingWd: 3,
      progress: null,
      blocked: false,
      nextAction: "Connect hydraulic lines, bleed steering circuit and check lock-to-lock clearance.",
      predecessors: ["ST-T2", "ST-HO-LT"],
      checklist: [
        { text: "Narrow hydraulic plumbing & full turn sweep checks", done: false },
        { text: "Wide hydraulic plumbing & full turn sweep checks", done: false }
      ]
    },
    {
      id: "ST-T4",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Steering / hydraulic functionality test (Narrow & Wide)",
      owner: "Mechanical Test & Validation",
      startDate: "2026-12-21",
      expectedFinishDate: "2026-12-25",
      durationWd: 5,
      remainingWd: 5,
      progress: null,
      blocked: false,
      nextAction: "Test steering effort, relief pressure, response time and turning radius.",
      predecessors: ["ST-T3", "ST-BUNDLE"],
      checklist: [
        { text: "Narrow steering performance & pressure verification", done: false },
        { text: "Wide steering performance & pressure verification", done: false }
      ]
    },
    {
      id: "ST-T5",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Endurance validation (Narrow & Wide)",
      owner: "Mechanical Test & Validation",
      startDate: "2026-12-28",
      expectedFinishDate: "2027-01-08",
      durationWd: 10,
      remainingWd: 10,
      progress: null,
      blocked: false,
      nextAction: "Run 100,000 steering cycle endurance bench test.",
      predecessors: ["ST-T4"],
      checklist: [
        { text: "Narrow endurance test completed without leakage/play", done: false },
        { text: "Wide endurance test completed without leakage/play", done: false }
      ]
    },
    {
      id: "ST-TR",
      lane: "steering",
      stream: "Steering",
      initiative: "INI-109505",
      title: "Prepare / approve Steering Serial TR",
      owner: "TPM / Engineering",
      startDate: "2027-01-11",
      expectedFinishDate: "2027-01-12",
      durationWd: 2,
      remainingWd: 2,
      progress: null,
      blocked: false,
      nextAction: "Sign off Steering Serial Technical Release for Narrow and Wide models.",
      predecessors: ["ST-VALID"],
      checklist: []
    }
  ],

  // ----------------- PURCHASING PROTOTYPES TRACKER -----------------
  // From 06_Prototypes sheet: 16 prototype items including variant parts
  prototypes: [
    {
      id: "PUR-01",
      partName: "Inverter Prototype",
      variant: "Common",
      initiative: "INI-109883",
      stream: "Mainstream",
      roadmapMilestoneId: "INV-M1",
      roadmapTaskId: "INV-02",
      supplier: "Curtis / Zapi",
      owner: "TPM / Purchasing",
      poReference: "PO-2026-9883",
      status: "Ready to order",
      sourcingDecision: "New part (spec ready)",
      orderPlacedDate: "2026-09-29",
      expectedDeliveryDate: "2026-10-27",
      dateType: "Supplier confirmed", // Estimated or Supplier confirmed
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Spec ready for PO release. Fast-track supplier discussion to secure 20 wd lead time."
    },
    {
      id: "PUR-02",
      partName: "UCB XS Prototype",
      variant: "Common",
      initiative: "INI-108827",
      stream: "Mainstream",
      roadmapMilestoneId: "UCB-M1",
      roadmapTaskId: "UCB-02",
      supplier: "Actia",
      owner: "TPM / Purchasing",
      poReference: "PO-2026-8827",
      status: "Ready to order",
      sourcingDecision: "New part (spec ready)",
      orderPlacedDate: "2026-09-29",
      expectedDeliveryDate: "2026-10-27",
      dateType: "Supplier confirmed",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Specification available. Prototype tooling on schedule."
    },
    {
      id: "PUR-03",
      partName: "Platform Prototype",
      variant: "COMPACT PULSAR",
      initiative: "INI-108827",
      stream: "Mainstream",
      roadmapMilestoneId: "PLT-M3",
      roadmapTaskId: "PLT-10",
      supplier: "Haulotte Fabrication",
      owner: "Mechanical Design",
      poReference: null, // Highlight orders without expected delivery date or PO
      status: "To confirm",
      sourcingDecision: "In-house prototype",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Awaiting design freeze on 2026-10-22 before tooling launch."
    },
    {
      id: "PUR-04",
      partName: "General Harness",
      variant: "Common",
      initiative: "INI-109883",
      stream: "Mainstream",
      roadmapMilestoneId: "SYS-M3",
      roadmapTaskId: "SYS-16",
      supplier: "Leoni",
      owner: "System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "New harness set",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-03",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Definition depends on System Review on 2026-11-02."
    },
    {
      id: "PUR-05",
      partName: "UP/DOWN Cable",
      variant: "Common",
      initiative: "INI-109883",
      stream: "Mainstream",
      roadmapMilestoneId: "SYS-M5",
      roadmapTaskId: "SYS-19",
      supplier: "Leoni",
      owner: "System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "New heavy-duty cable",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-03",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Fast-track preliminary definition underway for Mechanical routing feedback."
    },
    {
      id: "PUR-06",
      partName: "Spiral Cable",
      variant: "Common",
      initiative: "INI-109883",
      stream: "Mainstream",
      roadmapMilestoneId: "SP-M1",
      roadmapTaskId: "SP-02",
      supplier: "Internal Warehouse / Lapp",
      owner: "System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Carry-over vs New (TBD)",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-02",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Conservative 20 wd sourcing allowance. Will set to 0 wd once stock compatibility confirmed."
    },
    {
      id: "PUR-07",
      partName: "Narrow Chassis Prototype",
      variant: "Narrow",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-CH-AV",
      roadmapTaskId: "ST-CH-LT",
      supplier: "Haulotte Frame Shop",
      owner: "Mechanical Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Minimal chassis modification",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Design freeze required at Joint Review on 2026-10-22."
    },
    {
      id: "PUR-08",
      partName: "Narrow Pivot Set",
      variant: "Narrow",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-PV-AV",
      roadmapTaskId: "ST-PV-LT",
      supplier: "Chassieu Machining",
      owner: "Mechanical Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "New pivot brackets",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Machining tooling lead time 30 working days."
    },
    {
      id: "PUR-09",
      partName: "Narrow Steering Mechanism",
      variant: "Narrow",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-SM-AV",
      roadmapTaskId: "ST-SM-LT",
      supplier: "Chassieu Machining",
      owner: "Mechanical Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "New central link & tie rods",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Requires Joint Design review OK."
    },
    {
      id: "PUR-10",
      partName: "Narrow Hydraulic Cylinder",
      variant: "Narrow",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-CY-AV",
      roadmapTaskId: "ST-CY-LT",
      supplier: "Bucher / Hydac",
      owner: "Hydraulic System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Unconfirmed", // Carry-over vs New
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-11-25",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Unconfirmed decision D1-N. Uses 20 wd new-part allowance. Carry-over would cut lead time to 3 wd."
    },
    {
      id: "PUR-11",
      partName: "Narrow Hoses & Fittings",
      variant: "Narrow",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-HO-AV",
      roadmapTaskId: "ST-HO-LT",
      supplier: "Parker",
      owner: "Hydraulic System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Unconfirmed", // Carry-over vs New
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-11-25",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Unconfirmed decision D2-N. Target carry-over where feasible."
    },
    {
      id: "PUR-12",
      partName: "Wide Chassis Prototype",
      variant: "Wide",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-CH-AV",
      roadmapTaskId: "ST-CH-LT",
      supplier: "Haulotte Frame Shop",
      owner: "Mechanical Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Minimal chassis modification",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Wide frame adaptation definition in progress."
    },
    {
      id: "PUR-13",
      partName: "Wide Pivot Set",
      variant: "Wide",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-PV-AV",
      roadmapTaskId: "ST-PV-LT",
      supplier: "Chassieu Machining",
      owner: "Mechanical Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "New pivot brackets",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Same guiding principle as Narrow, adjusted for Wide axle gauge."
    },
    {
      id: "PUR-14",
      partName: "Wide Steering Mechanism",
      variant: "Wide",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-SM-AV",
      roadmapTaskId: "ST-SM-LT",
      supplier: "Chassieu Machining",
      owner: "Mechanical Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "New central link & tie rods",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-12-09",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Awaiting joint mechanical review."
    },
    {
      id: "PUR-15",
      partName: "Wide Hydraulic Cylinder",
      variant: "Wide",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-CY-AV",
      roadmapTaskId: "ST-CY-LT",
      supplier: "Bucher / Hydac",
      owner: "Hydraulic System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Unconfirmed",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-11-25",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Unconfirmed decision D1-W. Target carry-over feasibility."
    },
    {
      id: "PUR-16",
      partName: "Wide Hoses & Fittings",
      variant: "Wide",
      initiative: "INI-109505",
      stream: "Steering",
      roadmapMilestoneId: "ST-HO-AV",
      roadmapTaskId: "ST-HO-LT",
      supplier: "Parker",
      owner: "Hydraulic System Design",
      poReference: null,
      status: "To confirm",
      sourcingDecision: "Unconfirmed",
      orderPlacedDate: null,
      expectedDeliveryDate: "2026-11-25",
      dateType: "Estimated",
      receivedDate: null,
      acceptedForAssembly: false,
      issueNote: "Unconfirmed decision D2-W."
    }
  ],

  // ----------------- RAID & DECISIONS -----------------
  raid: [
    {
      id: "R1",
      type: "Risk",
      initiative: "INI-109883",
      lane: "CAN 2 Inverter / P2 XS UCB",
      description: "Electrical prototypes are supplied by different parties and not at the same pace.",
      consequence: "Integrated electrical set is not available together for System Test; system test slips.",
      probability: 4,
      impact: 4,
      score: 16,
      affectedWbs: "INV / UCB / SYS prototypes / TST-M1",
      owner: "TPM / Purchasing",
      status: "Open",
      action: "Synchronize prototype procurement and availability tracking across inverter, harness, UP/DOWN cable, spiral cable and UCB.",
      dueDate: "2026-10-15",
      decisionOutcome: ""
    },
    {
      id: "R2",
      type: "Risk",
      initiative: "INI-109883",
      lane: "CAN 2 Inverter / P2 XS UCB",
      description: "Interfaces across inverter, harnesses, UP/DOWN cable, spiral cable, UCB and software are not fully validated upfront.",
      consequence: "Integrated solution shows interface or functional issues during System Test, triggering rework loops.",
      probability: 3,
      impact: 5,
      score: 15,
      affectedWbs: "SYS / SW / TST",
      owner: "System + Software",
      status: "Open",
      action: "Early System + Software alignment and planned integrated review before test entry.",
      dueDate: "2026-10-22",
      decisionOutcome: ""
    },
    {
      id: "R3",
      type: "Risk",
      initiative: "INI-108827",
      lane: "Platform",
      description: "Platform concept must be checked against COMPACT options, labels and implantation constraints.",
      consequence: "Platform prototype reveals fit, option, or label-integration issues resulting in mechanical rework.",
      probability: 3,
      impact: 4,
      score: 12,
      affectedWbs: "PLT",
      owner: "Mechanical Design",
      status: "Open",
      action: "Review all applicable platform options and label implantation before design freeze on 2026-10-22.",
      dueDate: "2026-10-06",
      decisionOutcome: ""
    },
    {
      id: "R4",
      type: "Risk",
      initiative: "INI-109505",
      lane: "Steering",
      description: "Steering impacts chassis and hydraulics: Narrow/Wide chassis, cylinder, hoses and routing must converge.",
      consequence: "Steering prototype bundle is incomplete or fails functional/endurance testing, causing supplier redesign.",
      probability: 4,
      impact: 4,
      score: 16,
      affectedWbs: "ST-*",
      owner: "Mechanical + Hydraulic",
      status: "Open",
      action: "Run joint Mechanical + Hydraulic design review; track complete prototype bundle; target minimal chassis modifications and carry-over cylinder/hoses.",
      dueDate: "2026-10-22",
      decisionOutcome: ""
    },
    {
      id: "R5",
      type: "Risk",
      initiative: "INI-110093",
      lane: "Routing",
      description: "Routing depends on rapid clarification of the new UP/DOWN cable characteristics.",
      consequence: "Late cable definition delays routing updates; routing workstream loses fast-track advantage.",
      probability: 2,
      impact: 3,
      score: 6,
      affectedWbs: "RT / SYS-02",
      owner: "System Design",
      status: "Open",
      action: "Fast-track System Design feedback on UP/DOWN cable size and bend radius to Mechanical Design by 2026-10-05.",
      dueDate: "2026-10-05",
      decisionOutcome: ""
    },
    {
      id: "R6",
      type: "Risk",
      initiative: "INI-109883",
      lane: "CAN 2 Inverter / P2 XS UCB",
      description: "Backward compatibility of the new architecture is not yet confirmed (new inverter/cable with current UCB).",
      consequence: "Transition flexibility lost; multiple components must change simultaneously for test and factory rollout.",
      probability: 4,
      impact: 5,
      score: 20, // Highest concern in PPTX
      affectedWbs: "SYS-10 / SW-03",
      owner: "System + Software",
      status: "Open",
      action: "Ask technical teams to assess compatibility scenarios and software poka-yoke / configuration safeguards.",
      dueDate: "2026-10-19",
      decisionOutcome: ""
    },
    {
      id: "D1-N",
      type: "Decision",
      initiative: "INI-109505",
      lane: "Steering",
      description: "Narrow: Can an existing hydraulic cylinder be carried over?",
      consequence: "Changes chassis/hydraulic design, procurement lead time (3 wd carry-over vs 20 wd new) and cost.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "ST-N-CDEC",
      owner: "Hydraulic Design",
      status: "Open",
      action: "Complete kinematics sweep on Narrow chassis and verify stroke and force margins.",
      dueDate: "2026-10-09",
      decisionOutcome: "Unconfirmed"
    },
    {
      id: "D1-W",
      type: "Decision",
      initiative: "INI-109505",
      lane: "Steering",
      description: "Wide: Can an existing hydraulic cylinder be carried over?",
      consequence: "Changes chassis/hydraulic design, procurement lead time and cost.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "ST-W-CDEC",
      owner: "Hydraulic Design",
      status: "Open",
      action: "Complete kinematics sweep on Wide chassis and verify stroke and force margins.",
      dueDate: "2026-10-09",
      decisionOutcome: "Unconfirmed"
    },
    {
      id: "D2-N",
      type: "Decision",
      initiative: "INI-109505",
      lane: "Steering",
      description: "Narrow: Can existing hydraulic hoses / fittings be carried over?",
      consequence: "Changes routing, procurement lead time (3 wd carry-over vs 20 wd new) and unit cost.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "ST-N-HDEC",
      owner: "Hydraulic Design",
      status: "Open",
      action: "Verify hose length and connection fittings against Narrow 3D mock-up.",
      dueDate: "2026-10-09",
      decisionOutcome: "Unconfirmed"
    },
    {
      id: "D2-W",
      type: "Decision",
      initiative: "INI-109505",
      lane: "Steering",
      description: "Wide: Can existing hydraulic hoses / fittings be carried over?",
      consequence: "Changes routing, procurement lead time and unit cost.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "ST-W-HDEC",
      owner: "Hydraulic Design",
      status: "Open",
      action: "Verify hose length and connection fittings against Wide 3D mock-up.",
      dueDate: "2026-10-09",
      decisionOutcome: "Unconfirmed"
    },
    {
      id: "D3",
      type: "Decision",
      initiative: "INI-109505",
      lane: "Steering",
      description: "How far can chassis modifications be minimized for Narrow and Wide?",
      consequence: "Drives chassis welding fixture complexity, prototype tooling cost and timing.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "ST-D3",
      owner: "Mechanical Design",
      status: "Open",
      action: "Target zero main rail cut-outs; confine adaptation to front bolster mounting holes.",
      dueDate: "2026-10-16",
      decisionOutcome: "In progress - targeting minimal modifications"
    },
    {
      id: "D4",
      type: "Decision",
      initiative: "INI-109883",
      lane: "CAN 2 Inverter / P2 XS UCB",
      description: "Can new UP/DOWN cable work with current spiral cable + current UCB and later UCB XS?",
      consequence: "Determines progressive transition flexibility across factory assembly lines.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "SYS-07 / SYS-10",
      owner: "System Design",
      status: "Open",
      action: "Technical assessment of pin assignments and ground shielding.",
      dueDate: "2026-10-14",
      decisionOutcome: "Pending lab signal integrity test"
    },
    {
      id: "D5",
      type: "Decision",
      initiative: "INI-109883",
      lane: "CAN 2 Inverter / P2 XS UCB",
      description: "Can new inverter / control architecture work with current UCB?",
      consequence: "Determines whether UCB XS becomes a hard cut-over blocker for machine production.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "SYS-08 / SYS-10",
      owner: "System Design",
      status: "Open",
      action: "Validate CAN protocol backward translation options.",
      dueDate: "2026-10-16",
      decisionOutcome: "Pending protocol review"
    },
    {
      id: "D6",
      type: "Decision",
      initiative: "INI-109883",
      lane: "CAN 2 Inverter / P2 XS UCB",
      description: "Can software safely support current UCB and UCB XS selection/detection?",
      consequence: "Determines mixed-configuration safety and transition flexibility.",
      probability: 0,
      impact: 0,
      score: 0,
      affectedWbs: "SW-03",
      owner: "Software Design",
      status: "Open",
      action: "Implement hardware ID query handshake in bootloader.",
      dueDate: "2026-10-26",
      decisionOutcome: "Architecture approved, implementation in SW-03"
    }
  ],

  // Change audit log (Starts empty with first real update, per requirements)
  history: [],
  snapshots: []
};
